- name: Configuring the repo for mongodb
  ansible.builtin.template:
    src: mongod.repo
    dest: "{{ repo_path}}"

- name: Installing {{ component }}
  ansible.builtin.dnf:  
    name: mongodb-org
    state: present  

- name: making {{ component }} accessible
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restarting {{ component }} service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: mongod
    enabled: true

# Adding only for EKS deployment, can be removed for on-prem deployment
- name: Download and extract {{ component }} Schema
  ansible.builtin.unarchive:
    src: https://stan-robotshop.s3.amazonaws.com/shipping-v3.zip
    dest: /tmp
    remote_src: yes

- name: Installing mongodb shell
  ansible.builtin.dnf:  
    name: mongodb-mongosh
    state: present  

- name: Injecting schema 
  ansible.builtin.shell: mongosh --host mongodb-{{ env }}.roboshop.internal </tmp/db/master-data.js 

- name: Configuring hostname for {{ component }}
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname