- name: Installing {{ component }}
  ansible.builtin.dnf:  
    name: mysql-server
    state: present  

- name: Installing {{ component }}
  ansible.builtin.debug:  
    msg: This is {{ component }} role

- name: Installing vault pre-req package 
  ansible.builtin.shell: pip3.11 install hvac

- name: Restarting {{ component }} service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: mysqld
    enabled: true

- name: Configuring root password for {{ component }}
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ secrets.mysql_pass }}

# Added only for EKS deployment, can be removed for on-prem deployment
- name: Download and extract {{ component }} Schema
  ansible.builtin.unarchive:
    src: https://stan-robotshop.s3.amazonaws.com/shipping-v3.zip
    dest: /tmp
    remote_src: yes

- name: Injecting schema - Master data
  loop: "{{ schema }}"
  ansible.builtin.shell: mysql -h mysql-{{ env }}.roboshop.internal -uroot -p{{ secrets.mysql_pass }} < /tmp/db/{{ item }}.sql
  when: setup_schema is defined

- name: Configuring hostname for {{ component }}
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname